### ISSUE TITLE
Link broken

### ISSUE THREAD

**Issue by Penjogich** [speedskater/PolarFlowSynchronizerUI#1]
Thanks for this. It sorts out a major headache. However, although it gets all my sessions, it generates a file export.txt. It appears to be searching for the file in location e.g. "/training/analysis/249571280/export/tcx" instead of "/training/analysis/249571280/export/tcx/false".

![export_5](https://github-cloud.s3.amazonaws.com/assets/15183867/10565459/54998b32-75d9-11e5-9971-dcb3301b06bf.jpg)
![export_6](https://github-cloud.s3.amazonaws.com/assets/15183867/10565462/549ac54c-75d9-11e5-8966-d804abab24e6.jpg)
![export_7](https://github-cloud.s3.amazonaws.com/assets/15183867/10565461/549a6994-75d9-11e5-9e64-c139bec23413.jpg)
![export_8](https://github-cloud.s3.amazonaws.com/assets/15183867/10565460/5499de34-75d9-11e5-87a4-96ae5b31002a.jpg)
![export_1](https://github-cloud.s3.amazonaws.com/assets/15183867/10565463/549b3018-75d9-11e5-85c0-6d9df5211da8.jpg)
![export_2](https://github-cloud.s3.amazonaws.com/assets/15183867/10565464/549bf7a0-75d9-11e5-8584-e3099a3a7ded.jpg)
![export_3](https://github-cloud.s3.amazonaws.com/assets/15183867/10565465/54c919ba-75d9-11e5-91a1-6b02f1864aa9.jpg)
![export_4](https://github-cloud.s3.amazonaws.com/assets/15183867/10565467/54ca68ba-75d9-11e5-9cea-46d526e35767.jpg)
![export_13](https://github-cloud.s3.amazonaws.com/assets/15183867/10565468/54ca616c-75d9-11e5-8289-9b5e12d3a3f6.jpg)
![export_14](https://github-cloud.s3.amazonaws.com/assets/15183867/10565469/54cb2782-75d9-11e5-8553-f7cdcf7e655f.jpg)
![export_15](https://github-cloud.s3.amazonaws.com/assets/15183867/10565466/54c9953e-75d9-11e5-9f14-33abf51bc396.jpg)
![export_9](https://github-cloud.s3.amazonaws.com/assets/15183867/10565470/54cc5440-75d9-11e5-8e08-ace053062662.jpg)
![export_10](https://github-cloud.s3.amazonaws.com/assets/15183867/10565471/54f70212-75d9-11e5-91ea-2ee407deb557.jpg)
![export_11](https://github-cloud.s3.amazonaws.com/assets/15183867/10565472/54f7bd6a-75d9-11e5-8ee6-8a104d0eb2a1.jpg)
![export_12](https://github-cloud.s3.amazonaws.com/assets/15183867/10565473/54f7e9e8-75d9-11e5-8bc6-eecc7a7991b3.jpg)

**Comment by Penjogich** [comment]
This has been resolved by doing the following:
1. Go to

"C:\Your Program Files Directory\Polar Flow Synchronizer\node_modules\polar-flow-synchronizer\lib\PolarSynchronizer.js"
1. Open the file using notepad and search for the following which is line 89:
   var exportUrl = training.url + "/export/tcx/"
2. Replace the line with
   var exportUrl = training.url + "/export/tcx/false"
3. Save and re-open the program

**Comment by speedskater** [comment]
@Penjogich Thanks for reporting this bug. A fix is online and the new installer packages are available at this location: http://speedskater.github.io/PolarFlowSynchronizerUI/

**Comment by Penjogich** [comment]
Thanks a lot for this. Much appreciated.

**Comment by Penjogich** [comment]
Hi,

 

Over the last couple of days, I have been unable to download the tcx files using PolarFlowSynchronizerUI. (Please see screenshot and export report.)

 

Something must have changed. 

 

(I am able to manually download from https://flow.polar.com/training/analysis.)

 

Regards

Peter

 

From: Peter Gichuru Njoka <gichurupeter@gmail.com> 
Sent: 21 October 2015 20:56
To: 'speedskater/PolarFlowSynchronizerUI' <reply@reply.github.com>; 'speedskater/PolarFlowSynchronizerUI' <PolarFlowSynchronizerUI@noreply.github.com>
Subject: RE: [PolarFlowSynchronizerUI] Link broken (#1)

 

Thanks a lot for this. Much appreciated.
